"""Auto-generate a markdown pentest report from engagement data.

The report is just a render of the structured engagement (models.Engagement),
which is why the schema was worth getting right first.
"""
from __future__ import annotations

from pathlib import Path

from ghostops.config import load_config
from ghostops.memory.store import EngagementStore, list_engagements
from ghostops.models import Engagement, Severity

_SEV_ORDER = list(Severity)


def render_markdown(e: Engagement) -> str:
    lines: list[str] = []
    lines.append(f"# Penetration Test Report - {e.name or e.id}")
    lines.append("")
    lines.append(f"- **Engagement ID:** {e.id}")
    lines.append(f"- **Started:** {e.created_at}")
    lines.append(f"- **Final phase:** {e.phase.value}")
    lines.append(f"- **Scope:** {', '.join(e.scope) or '(none declared)'}")
    lines.append("")
    lines.append("> Conducted under written authorization. For the authorized "
                 "target scope only.")
    lines.append("")

    # ---- executive summary ----
    counts = e.counts()
    sev_counts: dict[str, int] = {}
    for f in e.findings:
        sev_counts[f.severity.value] = sev_counts.get(f.severity.value, 0) + 1
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(
        f"The assessment identified **{counts['hosts']} live host(s)**, "
        f"**{counts['ports']} open service(s)**, and "
        f"**{counts['findings']} finding(s)**."
    )
    if sev_counts:
        breakdown = ", ".join(
            f"{n} {s}" for s, n in sorted(
                sev_counts.items(),
                key=lambda kv: -_SEV_ORDER.index(Severity(kv[0])),
            )
        )
        lines.append(f"Severity breakdown: {breakdown}.")
    lines.append("")

    # ---- hosts & services ----
    lines.append("## Discovered Hosts & Services")
    lines.append("")
    if e.hosts:
        for h in e.hosts:
            hdr = f"### {h.ip}"
            if h.hostname:
                hdr += f" ({h.hostname})"
            lines.append(hdr)
            if h.os:
                lines.append(f"- OS: {h.os}")
            lines.append("")
            lines.append("| Port | Proto | Service | Version |")
            lines.append("|---|---|---|---|")
            for s in sorted(h.services, key=lambda x: x.port):
                lines.append(
                    f"| {s.port} | {s.proto} | {s.name} | {s.banner} |"
                )
            lines.append("")
    else:
        lines.append("_No hosts discovered._")
        lines.append("")

    # ---- findings ----
    lines.append("## Findings")
    lines.append("")
    if e.findings:
        for f in sorted(e.findings, key=lambda x: -x.severity.rank):
            loc = f"{f.host}:{f.port}" if f.port else f.host
            lines.append(f"### [{f.severity.value.upper()}] {f.title}")
            if loc.strip(":"):
                lines.append(f"- **Location:** {loc}")
            if f.source:
                lines.append(f"- **Source:** {f.source}")
            if f.references:
                lines.append(f"- **References:** {', '.join(f.references)}")
            if f.description:
                lines.append("")
                lines.append(f.description)
            lines.append("")
    else:
        lines.append("_No findings recorded._")
        lines.append("")

    # ---- credentials ----
    if e.credentials:
        lines.append("## Credentials Recovered")
        lines.append("")
        lines.append("| Service | Host | Username | Secret | Source |")
        lines.append("|---|---|---|---|---|")
        for c in e.credentials:
            lines.append(
                f"| {c.service} | {c.host} | {c.username} | "
                f"{c.secret} | {c.source} |"
            )
        lines.append("")

    # ---- methodology / activity log ----
    lines.append("## Methodology & Activity Log")
    lines.append("")
    if e.activity:
        lines.append("| Time | Type | Action |")
        lines.append("|---|---|---|")
        for a in e.activity:
            summary = a.summary.replace("|", "\\|")
            lines.append(f"| {a.timestamp} | {a.kind} | {summary} |")
        lines.append("")
    else:
        lines.append("_No activity recorded._")
        lines.append("")

    lines.append("## Remediation Recommendations")
    lines.append("")
    lines.append("- Patch outdated services identified above to current versions.")
    lines.append("- Enforce strong, unique credentials on all exposed services.")
    lines.append("- Restrict network exposure of administrative services.")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by GhostOps._")
    return "\n".join(lines)


def generate_report(engagement_id: str = "last",
                    output: str = "report.md") -> None:
    from rich.console import Console
    console = Console()
    cfg = load_config()
    eng_dir = cfg.get("engagements.dir", "./engagements")
    if engagement_id == "last":
        items = list_engagements(eng_dir)
        if not items:
            console.print("[yellow]No engagements found.[/yellow]")
            return
        engagement_id = sorted(items, key=lambda x: x["created_at"])[-1]["id"]
    store = EngagementStore(f"{eng_dir}/{engagement_id}.db")
    e = store.load()
    if e is None:
        console.print(f"[red]Engagement not found:[/red] {engagement_id}")
        return
    md = render_markdown(e)
    Path(output).write_text(md, encoding="utf-8")
    console.print(f"[green]Report written:[/green] {output} "
                  f"({len(md.splitlines())} lines)")
